tasks:
  - name: Frontend
    init: |
      cd frontend
      npm install
    command: |
      cd frontend
      npm run dev
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview
